DOC: jobs: Add missing word to error message

diff --git a/reproman/support/jobs/job_templates/submission/local.template b/reproman/support/jobs/job_templates/submission/local.template
--- a/reproman/support/jobs/job_templates/submission/local.template
+++ b/reproman/support/jobs/job_templates/submission/local.template
@@ -10,7 +10,7 @@ then
 else
     if test -z $(which parallel)
     then
-       echo "parallel (moreutils) is required to concurrent jobs locally" >&2
+       echo "parallel (moreutils) is required to run concurrent jobs locally" >&2
        exit 1
     fi
 
